# Generated by Django 3.0.8 on 2020-09-14 04:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection_Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(default=datetime.datetime.now, help_text='Enter collection date')),
            ],
            options={
                'verbose_name_plural': 'Collection Dates',
            },
        ),
        migrations.CreateModel(
            name='Collector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Collectors',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Family',
            },
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('province', models.CharField(max_length=50)),
                ('locality', models.CharField(max_length=50)),
                ('gps', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Photographer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Photographers',
            },
        ),
        migrations.CreateModel(
            name='Preparation1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Preparation 1',
            },
        ),
        migrations.CreateModel(
            name='Preparation2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preparation', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Preparation 2',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Specimen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_code', models.CharField(help_text='Enter complete collection code', max_length=50)),
                ('initial_ID', models.CharField(max_length=50, null=True)),
                ('final_ID', models.CharField(max_length=50)),
                ('dna_barcode', models.TextField(max_length=655)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('collection_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Collection_Date')),
                ('collector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Collector')),
                ('family', models.ForeignKey(help_text='Select appropriate family', on_delete=django.db.models.deletion.CASCADE, to='database.Family')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Locations')),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Photographer')),
                ('preparation_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Preparation1')),
                ('preparation_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Preparation2')),
                ('status', models.ForeignKey(default='Encoded', on_delete=django.db.models.deletion.CASCADE, to='database.Status')),
            ],
            options={
                'verbose_name_plural': 'Specimens',
            },
        ),
    ]
