# Generated by Django 3.0.8 on 2020-09-21 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20200918_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='collection_code',
            field=models.CharField(help_text='Enter complete collection code', max_length=50, unique=True),
        ),
    ]
