# Generated by Django 3.0.8 on 2020-09-22 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0003_auto_20200921_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSpecimen',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('collection_code', models.CharField(db_index=True, help_text='Enter complete collection code', max_length=50)),
                ('initial_ID', models.CharField(max_length=50, null=True)),
                ('final_ID', models.CharField(max_length=50)),
                ('dna_barcode', models.TextField(max_length=700)),
                ('date_created', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_updated', models.DateTimeField(blank=True, editable=False, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('author', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('collection_date', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Collection_Date')),
                ('collector', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Collector')),
                ('family', models.ForeignKey(blank=True, db_constraint=False, help_text='Select appropriate family', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Family')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Locations')),
                ('photographer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Photographer')),
                ('preparation_1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Preparation1')),
                ('preparation_2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Preparation2')),
                ('status', models.ForeignKey(blank=True, db_constraint=False, default='Encoded', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='database.Status')),
            ],
            options={
                'verbose_name': 'historical specimen',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
