# Generated by Django 3.0.8 on 2020-10-08 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_auto_20200922_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='identifer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.Identifier'),
        ),
    ]
