# Generated by Django 3.1.7 on 2022-04-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='identity',
            field=models.TextField(),
        ),
    ]
