# Generated by Django 3.1.7 on 2022-04-19 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_auto_20220419_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resultss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.CharField(default='', max_length=50)),
                ('collection_code', models.CharField(max_length=50)),
                ('identity', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Resultss',
            },
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Results'},
        ),
    ]
