# Generated by Django 3.1.7 on 2022-04-19 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0013_auto_20220419_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultss',
            name='identity',
            field=models.FloatField(),
        ),
    ]
