# Generated by Django 3.1.7 on 2022-04-25 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_auto_20220419_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='tissue',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.tissue'),
        ),
    ]
