# Generated by Django 3.1.7 on 2022-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0015_auto_20220425_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='dna_barcode',
            field=models.TextField(max_length=700, null=True),
        ),
    ]
