# Generated by Django 3.1.7 on 2022-05-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0016_auto_20220527_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specimen',
            name='dna_barcode',
            field=models.TextField(blank=True, default='', max_length=700),
        ),
    ]
