# Generated by Django 3.1.7 on 2022-05-27 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_auto_20220527_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultss',
            name='location',
            field=models.CharField(default='', max_length=50),
        ),
    ]
